### ISSUE TITLE
Seeking help for RHEL compatibility for spike

### ISSUE THREAD

**Issue by shraddha10101** [riscv/riscv-isa-sim#1070] opened 2022-08-18 13:12 UTC
Is spike compatible for RHEL machines?

**Comment by aswaterman** [comment] 2022-08-18 19:17
Although I can't provide support for specific machines, I can confirm I'm currently using Spike on an RHEL 8.5 machine.

**Comment by scottj97** [comment] 2022-12-05 12:10
Closing since question was answered and OP has not responded.

**Closed as completed by scottj97** 2022-12-05 12:10 UTC
