### ISSUE TITLE
[Bug Report] Memory access range of SPIKE

### ISSUE THREAD

**Issue by chenc6** [riscv/riscv-isa-sim#1011] opened 2022-05-24 20:33 UTC
Hi,

One of our test cases tries to access memory that is outside the accessible memory space (e.g., 0x12033000). However, the spike does not throw an exception for this behavior. 

Based on riscv/platform.h, below are the valid memory addresses:
![image](https://user-images.githubusercontent.com/79608200/170125492-5e375a17-c890-4907-8367-21ad96889c80.png)

Below is the output from the spike simulation:
![image](https://user-images.githubusercontent.com/79608200/170125868-4f9dc8bd-3f3b-4dfa-9c68-f2a90cc3728c.png)

The instructions at 0x800025c0 and 0x800025c0 changes the value of sp to 0x12033000, and instructions at 0x800000e4 and 0x800000f8 try to access data near that memory address. However, no exceptions are throwed.

test case and log files are attached.
[testcase.txt](https://github.com/riscv-software-src/riscv-isa-sim/files/8766042/testcase.txt)
[spike.log](https://github.com/riscv-software-src/riscv-isa-sim/files/8766043/spike.log)

Thank you.

**Comment by aswaterman** [comment] 2022-05-25 05:47
Unfortunately, this bug report isn't actionable without clear instructions on how to reproduce the bug.  You could try sharing with us the following:
- Which commit of this repo you used
- Your `configure` options
- Your `spike` command line
- The actual ELF binary you executed

**Comment by scottj97** [comment] 2022-11-08 02:56
Closing since no follow-up from OP

**Closed as not planned by scottj97** 2022-11-08 02:56 UTC
