### ISSUE TITLE
vfncvt.rod.f.f.w rounding to odd 

### ISSUE THREAD

**Issue by Kou66666** [riscv/riscv-isa-sim#1457] opened 2023-09-11 04:26 UTC
Hi,

riscv-isa-sim/softfloat/s_roundPackToF32.c, line 96 implement rounding to odd as following:

 96         if ( roundingMode == softfloat_round_odd ) {
 97             sig |= 1;

Does this means rod always or the fraction part bit0 to 1'b1? 

The correct behavior of rod suppose to be frac round up only:
1)  round > 0.5
2) if 0.5 & (guard bit == 0)

Kou

**Comment by aswaterman** [comment] 2023-09-11 19:44
Duplicate of https://github.com/ucb-bar/berkeley-softfloat-3/issues/20

**Closed as completed by aswaterman** 2023-09-11 19:44 UTC
